# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# see https://mmistakes.github.io/minimal-mistakes/docs/configuration/

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment


name: "Marco Costanzo"
title: Marco Costanzo
title_separator: "|"
subtitle: "Version 1.0"
email: marco.costanzo@unicampania.it
url: "https://marcocostanzo.github.io"
baseurl: ""
repository: "marcocostanzo/marcocostanzo.github.io"
description: >- # this means to ignore newlines until "baseurl:"
  Marco Costanzo, researcher (RTD-A) at Università degli studi della Campania "Luigi Vanvitelli"
# twitter_username: username
github_username: marcocostanzo
minimal_mistakes_skin: dark # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
search: true
locale: "en-US"
breadcrumbs: false # disabled by default

# SEO Related
google_site_verification : i7bq4nhg8HNjl9Z1XJFbXaR04SfL1l8r6xXHhD2gnz8
# bing_site_verification   :
# yandex_site_verification :

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# remote_theme: "mmistakes/minimal-mistakes@4.19.3"
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Rome # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Marco Costanzo"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : 'Researcher (RTD-A) at Università degli Studi della Campania "Luigi Vanvitelli".'
  location: "Italy"
  links:
    - label: "e-Mail"
      icon: "fas fa-envelope"
      url: "mailto:marco[dot]costanzo[at]unicampania[dot]it"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://marcocostanzo.github.io"
    - label: "Robotics Lab"
      icon: "fas fa-robot"
      url: "https://www.ingegneria.unicampania.it/roboticslab"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/marcocostanzo"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"
    - label: "ResearchGate"
      icon: "ai ai-researchgate"
      url: "https://www.researchgate.net/profile/Marco_Costanzo2"
    - label: "Scopus"
      icon: "ai ai-scopus"
      url: "https://www.scopus.com/authid/detail.uri?authorId=57205142585"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=32g4jFAAAAAJ"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0000-0001-8364-6728"
    - label: "Curriculum Vitae"
      icon: "ai ai-cv"
      url: "https://docs.google.com/viewer?url=https://github.com/marcocostanzo/assets/raw/main/cv/CostanzoMarco_cv_academic_EN.pdf"

footer:
  links:
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/marcocostanzo"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

collections:
  repositories:
    output: true
    permalink: /:collection/:path/
  courses:
    output: true
    permalink: /:collection/:path/
  awards:
    output: true
    permalink: /:collection/:path/

defaults:
  # home
  - scope:
      path: "index.html"
    values:
      #layout: search
      author_profile: true
      header:
        overlay_image: /assets/images/moon-earth.jpg
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      date_format: "%Y-%m-%d"
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      header:
        overlay_image: /assets/images/moon-earth.jpg
  # _repositories
  - scope:
      path: ""
      type: repositories
    values:
      layout: repository
      author_profile: false
      share: true
      header:
        teaser: http://via.placeholder.com/350
  # _courses
  - scope:
      path: ""
      type: courses
    values:
      layout: course
      author_profile: false
      share: true
      header:
        teaser: http://via.placeholder.com/350
  # _awards
  - scope:
      path: ""
      type: awards
    values:
      layout: single
      author_profile: false
      share: true
      header:
        teaser: /assets/images/award_teaser.svg


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
repositories_archive:
  type: liquid
  path: /repositories/
courses_archive:
  type: liquid
  path: /courses/
awards_archive:
  type: liquid
  path: /awards/
